---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: instavote
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: github-instavote
  timeout: 1m0s
  url: https://github.com/vesahc/instavote.git
