---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: result
  namespace: flux-system
spec:
  exclusionList:
  - ^.*\.sig$
  image: okimaw/result
  interval: 1m0s
  provider: generic
