---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: instavote
    kustomize.toolkit.fluxcd.io/namespace: instavote
  name: slack
  namespace: instavote
spec:
  channel: alerts
  secretRef:
    name: slack-url
  type: slack
