---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: instavote-all
  namespace: instavote
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@example.com
        name: flux
      messageTemplate: '{{range .Changed.Changes}}{{.OldValue}} -> {{.NewValue}}{{println}}{{end}}'
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  update:
    path: ./kustomize/vote/staging
    strategy: Setters
