apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: vote
  namespace: instavote
spec:
  provider: nginx
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vote
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: vote
  autoscalerRef:
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    name: vote
  progressDeadlineSeconds: 60
  service:
    port: 80
    targetPort: 80
