apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: vote
  namespace: instavote
spec:
  analysis:
    interval: 30s
    threshold: 10
    maxWeight: 50
    stepWeight: 5
    webhooks:
      - name: acceptance-test
        type: pre-rollout
        url: http://flagger-loadtester.flagger-system/
        timeout: 30s
        metadata:
          type: bash
          cmd: "curl http://vote-canary.instavote/ | grep choice"
      - name: load-test
        url: http://flagger-loadtester.flagger-system/
        timeout: 5s
        metadata:
          cmd: "hey -z 30s -q 10 -c 2 -host vote.example.com http://104.168.34.7"
